apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: guestbook-ui
spec:
  provider: istio
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: guestbook-ui
  progressDeadlineSeconds: 60
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: guestbook-ui
  service:
    port: 80
    portName: http-guestbook-ui
  skipAnalysis: false
  canaryAnalysis:
    # schedule interval (default 60s)
    interval: 10s
    # max number of failed metric checks before rollback
    threshold: 10
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    # Prometheus checks
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      threshold: 99
      interval: 10s
    - name: request-duration
      # maximum req duration P99
      # milliseconds
      threshold: 500
      interval: 5s
    webhooks:
    - name: load-test
      url: http://flagger-loadtester:8080/
      timeout: 5s
      metadata:
        cmd: "hey -z 1m -q 10 -c 2 http://guestbook-ui-canary:80/"
